### ISSUE TITLE
Are you give up windows version?

### ISSUE THREAD

**Issue by noahziheng** [Vatsinator/vatsinator-legacy#6]
Sir,
      I find you aren't release a newly version until v0.2.1 and it only can be compiled for linux by Wiki.What's up?

**Comment by garrappachc** [comment]
I am working on version 1.0 with a lot of major changes. Version 0.2.1 was built using MinGW and it is no longer supported - version 1.0 will be built by Visual Studio 2015. The wiki will be updated accordingly, when the version gets finally released.

**Comment by noahziheng** [comment]
Get it.Looking forward to newer version.And are the develop branch's files outdated?

**Comment by garrappachc** [comment]
No. Develop is actually the branch I am working on (master is for releases only), although I haven't pushed anything since 2 months, as I am doing some refactoring that I want to push in one commit. If you want to see how the progress goes, you may try the nightly build, though.

**Comment by noahziheng** [comment]
Thanks,waiting for that.
